---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: oracle-7.0
    driver:
      box: oraclelinux-7-x86_64
      box_url: http://cloud.terry.im/vagrant/oraclelinux-7-x86_64.box
      network:
        - ["private_network", {type: "dhcp"}]
      customize:
        memory: 2048
        cpus: 2


suites:
  - name: default
    run_list:
      - recipe[my_machine::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
